services:
  webfrontend:
    depends_on: 
      mywebapi:
        condition: service_healthy

  mywebapi:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m           # Time between health checks
      timeout: 3s            # Maximum time for a single health check
      retries: 3             # Number of retries before marking as unhealthy
      start_period: 10s      # Initial delay before health checks start