services:
  dotnet-web-applications:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    init: true
    networks:
      - app
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app
      
networks:
  app: