# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '**/docker-compose.dcproj'
      - '**/.dockerignore'
      - '**/README.md'
      - '.devcontainer/**'
      - '.vscode/**'
      - '.env'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore DotnetWebAppWithCompose.sln
    - name: Build
      run: dotnet build DotnetWebAppWithCompose.sln --no-restore
    - name: Test
      run: dotnet test DotnetWebAppWithCompose.sln --no-build --verbosity normal
